site_name: JetStream Documentation

pages:
- ['index.md', 'Home']
- ['using-images/UsingInstancesAndImages.md', 'Using Instances', 'Using Images and Launching Instances']
- ['using-volumes/UsingVolumes.md', 'Using Volumes', 'Using Volumes in Instances']

