site_name: JetStream Documentation

pages:
- ['index.md', 'Home']
- ['using-images/UsingImagesLaunchingInstances.md', 'Using Images and Launching Instances', 'Using Images and Launching Instances']
- ['using-images/LaunchNewInstance.md', 'Using Instances and Images', 'Launching New']
- ['using-images/LaunchNewInstance.md', '
